package com.lsv.lib.spring.core.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.PropertySource;

import static com.lsv.lib.core.helper.LibConstants.DEFAULT_ENCODING;
import static com.lsv.lib.core.helper.LibConstants.DEFAULT_PROPERTIES_FILE_NAME;
import static com.lsv.lib.spring.core.helper.ConstantsSpring.BASE_PACKAGE_SPRING;

/**
 * Autoconfiguration of spring's core module, which will be the basis for all projects using spring.
 * <p>
 * The @PropertySource annotation will load default settings from the default.properties file.
 * This file is generated by the properties-maven-plugin plugin contained in the Parent project's pom.xml.
 * It will include in this file the properties defined in all files pom.xml.
 *
 * @author Leandro da Silva Vieira
 * @PropertySource is the second lowest priority among the settings, so it won't impact the rest.
 * https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
 */
@Slf4j

@PropertySource(
    value = "classpath:/" + DEFAULT_PROPERTIES_FILE_NAME,
    ignoreResourceNotFound = true,
    encoding = DEFAULT_ENCODING
)
@ComponentScan(BASE_PACKAGE_SPRING)
@AutoConfiguration
public class SpringCoreAutoConfig {
}